{% set name = "powergenome" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9eb9b763beb26ce8f05670f7a20e9322309b8b7d27d796b187fdce2a3a6386cf

build:
  entry_points:
    - run_powergenome_multiple = powergenome.run_powergenome_multiple_outputs_cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=66,<68
    - wheel
    - pip
  run:
    - python >=3.8
    - catalystcoop.pudl >=0.6.0,<=2022.11.30
    - beautifulsoup4 >=4.8.13
    - statsmodels >=0.12.2
    - python-dotenv
    - flatten-dict
    - ruamel.yaml
    - pyyaml
    - frozendict
    - openpyxl >=3.0
    - geopandas >=0.11

test:
  imports:
    - powergenome
  commands:
    - pip check
    - run_powergenome_multiple --help
  requires:
    - pip

about:
  home: https://github.com/PowerGenome/PowerGenome
  summary: Create power system inputs for capacity expansion models
  dev_url: https://github.com/PowerGenome/PowerGenome
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - gschivley
